package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String rucOcedula;
     private String nombre;
     private String direccion;
     private String telefono;

    public Cliente() {
    }

	
    public Cliente(String rucOcedula) {
        this.rucOcedula = rucOcedula;
    }
    public Cliente(String rucOcedula, String nombre, String direccion, String telefono) {
       this.rucOcedula = rucOcedula;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getRucOcedula() {
        return this.rucOcedula;
    }
    
    public void setRucOcedula(String rucOcedula) {
        this.rucOcedula = rucOcedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


