package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Comprobanteretencion generated by hbm2java
 */
public class Comprobanteretencion  implements java.io.Serializable {


     private String numeroComprobanteRetencion;
     private String mes;
     private String anio;
     private String baseImponible;
     private String impuesto;
     private String porcentaje;
     private String totalRetenio;

    public Comprobanteretencion() {
    }

	
    public Comprobanteretencion(String numeroComprobanteRetencion) {
        this.numeroComprobanteRetencion = numeroComprobanteRetencion;
    }
    public Comprobanteretencion(String numeroComprobanteRetencion, String mes, String anio, String baseImponible, String impuesto, String porcentaje, String totalRetenio) {
       this.numeroComprobanteRetencion = numeroComprobanteRetencion;
       this.mes = mes;
       this.anio = anio;
       this.baseImponible = baseImponible;
       this.impuesto = impuesto;
       this.porcentaje = porcentaje;
       this.totalRetenio = totalRetenio;
    }
   
    public String getNumeroComprobanteRetencion() {
        return this.numeroComprobanteRetencion;
    }
    
    public void setNumeroComprobanteRetencion(String numeroComprobanteRetencion) {
        this.numeroComprobanteRetencion = numeroComprobanteRetencion;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getBaseImponible() {
        return this.baseImponible;
    }
    
    public void setBaseImponible(String baseImponible) {
        this.baseImponible = baseImponible;
    }
    public String getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(String impuesto) {
        this.impuesto = impuesto;
    }
    public String getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(String porcentaje) {
        this.porcentaje = porcentaje;
    }
    public String getTotalRetenio() {
        return this.totalRetenio;
    }
    
    public void setTotalRetenio(String totalRetenio) {
        this.totalRetenio = totalRetenio;
    }




}


