package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private String idContrato;
     private String dia;
     private String mes;
     private String anio;
     private String empresa;
     private String liquidoRecivido;

    public Contrato() {
    }

	
    public Contrato(String idContrato) {
        this.idContrato = idContrato;
    }
    public Contrato(String idContrato, String dia, String mes, String anio, String empresa, String liquidoRecivido) {
       this.idContrato = idContrato;
       this.dia = dia;
       this.mes = mes;
       this.anio = anio;
       this.empresa = empresa;
       this.liquidoRecivido = liquidoRecivido;
    }
   
    public String getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(String idContrato) {
        this.idContrato = idContrato;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getLiquidoRecivido() {
        return this.liquidoRecivido;
    }
    
    public void setLiquidoRecivido(String liquidoRecivido) {
        this.liquidoRecivido = liquidoRecivido;
    }




}


