package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Detalleegreso generated by hbm2java
 */
public class Detalleegreso  implements java.io.Serializable {


     private String idDetalleEgreso;
     private String concepto;
     private String valor;
     private String tipo;
     private String idContrato;

    public Detalleegreso() {
    }

	
    public Detalleegreso(String idDetalleEgreso) {
        this.idDetalleEgreso = idDetalleEgreso;
    }
    public Detalleegreso(String idDetalleEgreso, String concepto, String valor, String tipo, String idContrato) {
       this.idDetalleEgreso = idDetalleEgreso;
       this.concepto = concepto;
       this.valor = valor;
       this.tipo = tipo;
       this.idContrato = idContrato;
    }
   
    public String getIdDetalleEgreso() {
        return this.idDetalleEgreso;
    }
    
    public void setIdDetalleEgreso(String idDetalleEgreso) {
        this.idDetalleEgreso = idDetalleEgreso;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(String idContrato) {
        this.idContrato = idContrato;
    }




}


