package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Facturaegreso generated by hbm2java
 */
public class Facturaegreso  implements java.io.Serializable {


     private String numeroFactura;
     private String dia;
     private String mes;
     private String anio;
     private String proveedor;
     private String tipoBienOservicio;
     private String subtotal0;
     private String subtotalIva;
     private String derechoAcredito;
     private String tipoDeGasto;
     private String deducible;
     private String total;

    public Facturaegreso() {
    }

	
    public Facturaegreso(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Facturaegreso(String numeroFactura, String dia, String mes, String anio, String proveedor, String tipoBienOservicio, String subtotal0, String subtotalIva, String derechoAcredito, String tipoDeGasto, String deducible, String total) {
       this.numeroFactura = numeroFactura;
       this.dia = dia;
       this.mes = mes;
       this.anio = anio;
       this.proveedor = proveedor;
       this.tipoBienOservicio = tipoBienOservicio;
       this.subtotal0 = subtotal0;
       this.subtotalIva = subtotalIva;
       this.derechoAcredito = derechoAcredito;
       this.tipoDeGasto = tipoDeGasto;
       this.deducible = deducible;
       this.total = total;
    }
   
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getTipoBienOservicio() {
        return this.tipoBienOservicio;
    }
    
    public void setTipoBienOservicio(String tipoBienOservicio) {
        this.tipoBienOservicio = tipoBienOservicio;
    }
    public String getSubtotal0() {
        return this.subtotal0;
    }
    
    public void setSubtotal0(String subtotal0) {
        this.subtotal0 = subtotal0;
    }
    public String getSubtotalIva() {
        return this.subtotalIva;
    }
    
    public void setSubtotalIva(String subtotalIva) {
        this.subtotalIva = subtotalIva;
    }
    public String getDerechoAcredito() {
        return this.derechoAcredito;
    }
    
    public void setDerechoAcredito(String derechoAcredito) {
        this.derechoAcredito = derechoAcredito;
    }
    public String getTipoDeGasto() {
        return this.tipoDeGasto;
    }
    
    public void setTipoDeGasto(String tipoDeGasto) {
        this.tipoDeGasto = tipoDeGasto;
    }
    public String getDeducible() {
        return this.deducible;
    }
    
    public void setDeducible(String deducible) {
        this.deducible = deducible;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


