package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Facturaingreso generated by hbm2java
 */
public class Facturaingreso  implements java.io.Serializable {


     private String numeroFactura;
     private String tipoFactura;
     private String dia;
     private String mes;
     private String anio;
     private String coorX;
     private String coorY;
     private String cliente;
     private String subtotalValor0;
     private String subtotalValorIva;
     private String total;
     private String comprobanteDeRetencion;

    public Facturaingreso() {
    }

	
    public Facturaingreso(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Facturaingreso(String numeroFactura, String tipoFactura, String dia, String mes, String anio, String coorX, String coorY, String cliente, String subtotalValor0, String subtotalValorIva, String total, String comprobanteDeRetencion) {
       this.numeroFactura = numeroFactura;
       this.tipoFactura = tipoFactura;
       this.dia = dia;
       this.mes = mes;
       this.anio = anio;
       this.coorX = coorX;
       this.coorY = coorY;
       this.cliente = cliente;
       this.subtotalValor0 = subtotalValor0;
       this.subtotalValorIva = subtotalValorIva;
       this.total = total;
       this.comprobanteDeRetencion = comprobanteDeRetencion;
    }
   
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(String tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getCoorX() {
        return this.coorX;
    }
    
    public void setCoorX(String coorX) {
        this.coorX = coorX;
    }
    public String getCoorY() {
        return this.coorY;
    }
    
    public void setCoorY(String coorY) {
        this.coorY = coorY;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getSubtotalValor0() {
        return this.subtotalValor0;
    }
    
    public void setSubtotalValor0(String subtotalValor0) {
        this.subtotalValor0 = subtotalValor0;
    }
    public String getSubtotalValorIva() {
        return this.subtotalValorIva;
    }
    
    public void setSubtotalValorIva(String subtotalValorIva) {
        this.subtotalValorIva = subtotalValorIva;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public String getComprobanteDeRetencion() {
        return this.comprobanteDeRetencion;
    }
    
    public void setComprobanteDeRetencion(String comprobanteDeRetencion) {
        this.comprobanteDeRetencion = comprobanteDeRetencion;
    }




}


