package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Representante generated by hbm2java
 */
public class Representante  implements java.io.Serializable {


     private String numeroDeIdentificacionDelContribuyente;
     private String nombre;
     private String apellido;
     private String tipoDeIdentificacionDelContribuyenteORepresentanteLegal;
     private String correoElectronico;

    public Representante() {
    }

	
    public Representante(String numeroDeIdentificacionDelContribuyente) {
        this.numeroDeIdentificacionDelContribuyente = numeroDeIdentificacionDelContribuyente;
    }
    public Representante(String numeroDeIdentificacionDelContribuyente, String nombre, String apellido, String tipoDeIdentificacionDelContribuyenteORepresentanteLegal, String correoElectronico) {
       this.numeroDeIdentificacionDelContribuyente = numeroDeIdentificacionDelContribuyente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipoDeIdentificacionDelContribuyenteORepresentanteLegal = tipoDeIdentificacionDelContribuyenteORepresentanteLegal;
       this.correoElectronico = correoElectronico;
    }
   
    public String getNumeroDeIdentificacionDelContribuyente() {
        return this.numeroDeIdentificacionDelContribuyente;
    }
    
    public void setNumeroDeIdentificacionDelContribuyente(String numeroDeIdentificacionDelContribuyente) {
        this.numeroDeIdentificacionDelContribuyente = numeroDeIdentificacionDelContribuyente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTipoDeIdentificacionDelContribuyenteORepresentanteLegal() {
        return this.tipoDeIdentificacionDelContribuyenteORepresentanteLegal;
    }
    
    public void setTipoDeIdentificacionDelContribuyenteORepresentanteLegal(String tipoDeIdentificacionDelContribuyenteORepresentanteLegal) {
        this.tipoDeIdentificacionDelContribuyenteORepresentanteLegal = tipoDeIdentificacionDelContribuyenteORepresentanteLegal;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }




}


