package hibernate;
// Generated 22-sep-2011 10:49:33 by Hibernate Tools 3.2.1.GA



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String numeroDeIdentificacionDelUsuario;
     private String nombre;
     private String apellido;
     private String tipoDeIdentificacionDelUsuario;
     private String numeroDeIdentificacionDelContribuyente;
     private String clave;
     private String razonSocial;
     private String periodoDeDeclaracionDeIva;
     private String correoElectronico;
     private String provincia;
     private String ciudad;
     private String alertaCorreoIva;
     private String alertaCorreoIr;

    public Usuario() {
    }

	
    public Usuario(String numeroDeIdentificacionDelUsuario) {
        this.numeroDeIdentificacionDelUsuario = numeroDeIdentificacionDelUsuario;
    }
    public Usuario(String numeroDeIdentificacionDelUsuario, String nombre, String apellido, String tipoDeIdentificacionDelUsuario, String numeroDeIdentificacionDelContribuyente, String clave, String razonSocial, String periodoDeDeclaracionDeIva, String correoElectronico, String provincia, String ciudad, String alertaCorreoIva, String alertaCorreoIr) {
       this.numeroDeIdentificacionDelUsuario = numeroDeIdentificacionDelUsuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.tipoDeIdentificacionDelUsuario = tipoDeIdentificacionDelUsuario;
       this.numeroDeIdentificacionDelContribuyente = numeroDeIdentificacionDelContribuyente;
       this.clave = clave;
       this.razonSocial = razonSocial;
       this.periodoDeDeclaracionDeIva = periodoDeDeclaracionDeIva;
       this.correoElectronico = correoElectronico;
       this.provincia = provincia;
       this.ciudad = ciudad;
       this.alertaCorreoIva = alertaCorreoIva;
       this.alertaCorreoIr = alertaCorreoIr;
    }
   
    public String getNumeroDeIdentificacionDelUsuario() {
        return this.numeroDeIdentificacionDelUsuario;
    }
    
    public void setNumeroDeIdentificacionDelUsuario(String numeroDeIdentificacionDelUsuario) {
        this.numeroDeIdentificacionDelUsuario = numeroDeIdentificacionDelUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTipoDeIdentificacionDelUsuario() {
        return this.tipoDeIdentificacionDelUsuario;
    }
    
    public void setTipoDeIdentificacionDelUsuario(String tipoDeIdentificacionDelUsuario) {
        this.tipoDeIdentificacionDelUsuario = tipoDeIdentificacionDelUsuario;
    }
    public String getNumeroDeIdentificacionDelContribuyente() {
        return this.numeroDeIdentificacionDelContribuyente;
    }
    
    public void setNumeroDeIdentificacionDelContribuyente(String numeroDeIdentificacionDelContribuyente) {
        this.numeroDeIdentificacionDelContribuyente = numeroDeIdentificacionDelContribuyente;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getPeriodoDeDeclaracionDeIva() {
        return this.periodoDeDeclaracionDeIva;
    }
    
    public void setPeriodoDeDeclaracionDeIva(String periodoDeDeclaracionDeIva) {
        this.periodoDeDeclaracionDeIva = periodoDeDeclaracionDeIva;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getAlertaCorreoIva() {
        return this.alertaCorreoIva;
    }
    
    public void setAlertaCorreoIva(String alertaCorreoIva) {
        this.alertaCorreoIva = alertaCorreoIva;
    }
    public String getAlertaCorreoIr() {
        return this.alertaCorreoIr;
    }
    
    public void setAlertaCorreoIr(String alertaCorreoIr) {
        this.alertaCorreoIr = alertaCorreoIr;
    }




}


