package Modelo;
// Generated 09/02/2011 03:56:32 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Noticia generated by hbm2java
 */
public class Noticia  implements java.io.Serializable {


     private int idnoticia;
     private int idempleado;
     private int idseccion;
     private int idrecursoMultimedio;
     private Date fechaNoticia;
     private String provincia;
     private String canton;
     private String direccion;
     private String titulo;
     private String noticiaCorta;
     private String noticiaCompleta;
     private String palabraClave;
     private String estado;
     private double latitud;
     private double longitud;

    public Noticia() {
    }

    public Noticia(int idnoticia, int idempleado, int idseccion, int idrecursoMultimedio, Date fechaNoticia, String provincia, String canton, String direccion, String titulo, String noticiaCorta, String noticiaCompleta, String palabraClave, String estado, double latitud, double longitud) {
       this.idnoticia = idnoticia;
       this.idempleado = idempleado;
       this.idseccion = idseccion;
       this.idrecursoMultimedio = idrecursoMultimedio;
       this.fechaNoticia = fechaNoticia;
       this.provincia = provincia;
       this.canton = canton;
       this.direccion = direccion;
       this.titulo = titulo;
       this.noticiaCorta = noticiaCorta;
       this.noticiaCompleta = noticiaCompleta;
       this.palabraClave = palabraClave;
       this.estado = estado;
       this.latitud = latitud;
       this.longitud = longitud;
    }
   
    public int getIdnoticia() {
        return this.idnoticia;
    }
    
    public void setIdnoticia(int idnoticia) {
        this.idnoticia = idnoticia;
    }
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public int getIdseccion() {
        return this.idseccion;
    }
    
    public void setIdseccion(int idseccion) {
        this.idseccion = idseccion;
    }
    public int getIdrecursoMultimedio() {
        return this.idrecursoMultimedio;
    }
    
    public void setIdrecursoMultimedio(int idrecursoMultimedio) {
        this.idrecursoMultimedio = idrecursoMultimedio;
    }
    public Date getFechaNoticia() {
        return this.fechaNoticia;
    }
    
    public void setFechaNoticia(Date fechaNoticia) {
        this.fechaNoticia = fechaNoticia;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getNoticiaCorta() {
        return this.noticiaCorta;
    }
    
    public void setNoticiaCorta(String noticiaCorta) {
        this.noticiaCorta = noticiaCorta;
    }
    public String getNoticiaCompleta() {
        return this.noticiaCompleta;
    }
    
    public void setNoticiaCompleta(String noticiaCompleta) {
        this.noticiaCompleta = noticiaCompleta;
    }
    public String getPalabraClave() {
        return this.palabraClave;
    }
    
    public void setPalabraClave(String palabraClave) {
        this.palabraClave = palabraClave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }




}


