package Modelo;
// Generated 09/02/2011 03:56:32 AM by Hibernate Tools 3.2.1.GA



/**
 * RecursoMultimedio generated by hbm2java
 */
public class RecursoMultimedio  implements java.io.Serializable {


     private int idrecursoMultimedio;
     private String tipo;
     private String archivo;
     private String descripcion;
     private String estado;

    public RecursoMultimedio() {
    }

    public RecursoMultimedio(int idrecursoMultimedio, String tipo, String archivo, String descripcion, String estado) {
       this.idrecursoMultimedio = idrecursoMultimedio;
       this.tipo = tipo;
       this.archivo = archivo;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdrecursoMultimedio() {
        return this.idrecursoMultimedio;
    }
    
    public void setIdrecursoMultimedio(int idrecursoMultimedio) {
        this.idrecursoMultimedio = idrecursoMultimedio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


