package EntidadesBD;
// Generated 30-ene-2012 12:11:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private long idArticulo;
     private String titulo;
     private String contenido;
     private String tipo;
     private Set rols = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(long idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Articulo(long idArticulo, String titulo, String contenido, String tipo, Set rols) {
       this.idArticulo = idArticulo;
       this.titulo = titulo;
       this.contenido = contenido;
       this.tipo=tipo;
       this.rols = rols;
    }
   
    public long getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(long idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


