package EntidadesBD;
// Generated 30-ene-2012 12:11:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private long idPermiso;
     private String nombre;
     private Set rols = new HashSet(0);

    public Permiso() {
    }

	
    public Permiso(long idPermiso) {
        this.idPermiso = idPermiso;
    }
    public Permiso(long idPermiso, String nombre, Set rols) {
       this.idPermiso = idPermiso;
       this.nombre = nombre;
       this.rols = rols;
    }
   
    public long getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(long idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }




}


