package EntidadesBD;
// Generated 30-ene-2012 12:11:04 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private long idProducto;
     private String marca;
     private String modelo;
     private String categoria;
     private String tipo;
     private BigDecimal precio;
     private String path;
     private Set rols = new HashSet(0);

    public Producto() {
    }

	
    public Producto(long idProducto) {
        this.idProducto = idProducto;
    }
    public Producto(long idProducto, String marca,String modelo, String categoria, String tipo, BigDecimal precio, String path, Set rols) {
       this.idProducto = idProducto;
       this.marca = marca;
       this.modelo = modelo;
       this.categoria = categoria;
       this.tipo = tipo;
       this.precio = precio;
       this.path = path;
       this.rols = rols;
    }
   
    public long getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(long idProducto) {
        this.idProducto = idProducto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }




}


