package EntidadesBD;
// Generated 30-ene-2012 12:11:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private long idRol;
     private String nombre;
     private Set permisos = new HashSet(0);
     private Set productos = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set temas = new HashSet(0);
     private Set articulos = new HashSet(0);

    public Rol() {
    }

	
    public Rol(long idRol) {
        this.idRol = idRol;
    }
    public Rol(long idRol, String nombre, Set permisos, Set productos, Set usuarios, Set temas, Set articulos) {
       this.idRol = idRol;
       this.nombre = nombre;
       this.permisos = permisos;
       this.productos = productos;
       this.usuarios = usuarios;
       this.temas = temas;
       this.articulos = articulos;
    }
   
    public long getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(long idRol) {
        this.idRol = idRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getTemas() {
        return this.temas;
    }
    
    public void setTemas(Set temas) {
        this.temas = temas;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


