package EntidadesBD;
// Generated 30-ene-2012 12:11:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private long idTema;
     private String nombre;
     private String descripcion;
     private String path;
     private Set rols = new HashSet(0);

    public Tema() {
    }

	
    public Tema(long idTema) {
        this.idTema = idTema;
    }
    public Tema(long idTema, String nombre, String descripcion, String path, Set rols) {
       this.idTema = idTema;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.path = path;
       this.rols = rols;
    }
   
    public long getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(long idTema) {
        this.idTema = idTema;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        this.rols = rols;
    }




}


